image: Visual Studio 2017
branches:
  only:
  - master
  - develop
install:
  - cinst gitversion.portable -y
before_build:
  - nuget restore
  - ps: $env:VERSION=$(gitversion /showvariable NuGetVersionV2)
build_script:
  - ps: dotnet restore
  - ps: cd src/TimeIt; dotnet setversion $env:VERSION; cd ../..
  - ps: dotnet build
  - ps: dotnet pack --include-source --include-symbols -c Release -o out/
test_script:
  - ps: cd test/TimeIt.Tests; dotnet test -c Release
artifacts:
  path: src/TimeIt/out/*.nupkg
  name: NuGet packages
deploy:
  provider: NuGet
  skip_symbols: false
  api_key:
    secure: USCwZe1eILJaDmG30VFhlFWmr2P0G6o0HhUau72/W+TzyAMZyqEfL//vQhfjTSKP
  artifact: NuGet packages
  on:
    branch: master